name: 'release'

on: 'workflow_dispatch'

jobs:
    pre-release:
        name: 'Release'
        runs-on: 'ubuntu-latest'

        steps:
            # ...
            - name: 'Build'
              run: npm run build

            - uses: technote-space/release-github-actions@v6
